all: statistics_predictor
CC = g++
INSTDIR = 
INCLUDE = .
CFLAGS = 

statistics_predictor: main.cc
	$(CC) -o a.out main.cc

	
clean: 
	rm a.out

#install: socket_test
#	if( -d $(INSTDIR)) then\
#		echo "test"\
#	endif
